site_name: 雨世界modding
theme:
  logo: assets/rainworld-title.png
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: zh-Hant
  font:
    text: Noto Sans Simplified Chinese
    code: Fira Mono
  name : material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
       note: fontawesome/solid/note-sticky
       abstract: fontawesome/solid/book
       info: fontawesome/solid/circle-info
       tip: fontawesome/solid/bullhorn
       success: fontawesome/solid/check
       question: fontawesome/solid/circle-question
       warning: fontawesome/solid/triangle-exclamation
       failure: fontawesome/solid/bomb
       danger: fontawesome/solid/skull
       bug: fontawesome/solid/robot
       example: fontawesome/solid/flask
       quote: fontawesome/solid/quote-left
  features:
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer

repo_url: https://github.com/rwmoddingch/ChModdingWiki
repo_name: rwmoddingch/ChModdingWiki

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - 欢迎: index.md
  - 基础教程:
    - 欢迎来到基础教程: 基础教程/欢迎来到基础教程.md
    - module的概念: 基础教程/module的概念.md
    - ILhook教程 : 基础教程/IL简易教程.md
  - 深入雨世界:
    - 准备深入雨世界: 深入雨世界/准备深入雨世界.md
    - 绘制方法入门: 深入雨世界/绘制方法入门.md
  - 一些重要的mod:
    - SlugBase教程:
      - 序言: 一些重要的mod/slugbase教程/序言.md
      - 下载模板: 一些重要的mod/slugbase教程/下载模板.md
      - 准备工作: 一些重要的mod/slugbase教程/准备工作.md